Replace deprecated sys_siglist with strsignal
greenbone/gvmd pull request #1280
Opened 2020-08-31 14:40 UTC by tgurr

Required to work with glibc >= 2.32.

https://sourceware.org/pipermail/libc-announce/2020/000029.html

  The deprecated arrays sys_siglist, _sys_siglist, and sys_sigabbrev
  are no longer available to newly linked binaries, and their declarations
  have been removed from <string.h>. They are exported solely as
  compatibility symbols to support old binaries. All programs should use
  strsignal instead.

**What**: N/A

**Why**: https://github.com/greenbone/gvmd/issues/1279

**How**: N/A

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/gvmd/blob/master/CHANGELOG.md) Entry

2020-08-31 16:24 UTC, mattmundell requested changes
Thanks.

If you want this in the next 20.08 release then please submit a PR against gvmd-20.08 instead.

And would be great if you could add a CHANGELOG.md entry.

2020-08-31 16:33 UTC, tgurr commented
> If you want this in the next 20.08 release then please submit a PR against gvmd-20.08 instead.

I'll open a follow-up PR once this is through.

> And would be great if you could add a CHANGELOG.md entry.

Added.

2020-08-31 17:37 UTC, mattmundell commented
> > If you want this in the next 20.08 release then please submit a PR against gvmd-20.08 instead.
> 
> I'll open a follow-up PR once this is through.
> 
> > And would be great if you could add a CHANGELOG.md entry.
> 
> Added.

2020-08-31 17:39 UTC, mattmundell commented
> I'll open a follow-up PR once this is through.

I think just gvmd-20.08 would be easier, because we'll merge that to master.

2020-09-01 08:21 UTC, tgurr commented
> > I'll open a follow-up PR once this is through.
> 
> I think just gvmd-20.08 would be easier, because we'll merge that to master.

Took me a moment to figure out, I hope I did everything correctly switching the PR to gvmd-20.08.

2020-09-01 11:33 UTC, mattmundell requested changes
Yes, that's great, thank you.

One nitpick left, just noticed the missing spaces.

2020-09-01 11:33 UTC, mattmundell commented on src/gvmd.c
> +                   strsignal(termination_signal));
```suggestion
                   strsignal (termination_signal));
```

2020-09-01 11:33 UTC, mattmundell commented on src/gvmd.c
> +                   strsignal(termination_signal));
```suggestion
                   strsignal (termination_signal));
```

2020-09-01 11:33 UTC, mattmundell commented on src/manage_sql.c
> +  g_debug ("Received %s signal", strsignal(signal));
```suggestion
  g_debug ("Received %s signal", strsignal (signal));
```

2020-09-01 11:33 UTC, mattmundell commented on src/utils.c
> +                  __func__, strsignal(signal));
```suggestion
                  __func__, strsignal (signal));
```

2020-09-01 11:33 UTC, mattmundell commented on src/utils.c
> +                  __func__, strsignal(signal));
```suggestion
                  __func__, strsignal (signal));
```

2020-09-01 12:51 UTC, mattmundell approved these changes

2020-09-01 12:51 UTC, merged