Reduce severity classes
greenbone/gvmd pull request #1288
Opened 2020-09-05 15:26 UTC by janowagner

The support for multiple severity class ranges is removed.
There is now only one classification scheme (then one previously
called "nist"). Actually there was only one other classification scheme called
"pci-dss". It wasn't used or needed.

With applying a single default scheme code and database operations can
be simplified.

Basically all code elements are removed, including a migrator
that removes any such setting from the database.

The "report" XML element does not include the severity classification with
its range details (as element ""severity_class) anymore and the "authenticate_reponse"
XML does not include the "severity" element anymore.

**Checklist**:

- [ ] Tests N/A
- [ ] [CHANGELOG](https://github.com/greenbone/gvmd/blob/master/CHANGELOG.md) Entry

2020-09-14 15:19 UTC, mattmundell requested changes

2020-09-14 15:19 UTC, mattmundell commented on src/manage_pg.c
> -           "               WHEN 'medium'"
Missing medium now?

2020-09-14 15:19 UTC, mattmundell commented on src/manage_pg.c
> +           "              (SELECT CASE lower ($2)"
```suggestion
           "  SELECT CASE lower ($2)"
```

2020-09-14 15:19 UTC, mattmundell commented on src/manage_pg.c
>             "               WHEN 'high'"
```suggestion
           "         WHEN 'high'"
```
etc

2020-09-14 15:19 UTC, mattmundell commented on src/manage_pg.c
> +           "              (SELECT CASE lower ($2)"
Indenting as before.

2020-09-14 15:20 UTC, mattmundell commented
Also, it's missing the changes to the GMP doc.

2020-09-16 13:38 UTC, janowagner commented on src/manage_pg.c
> -           "               WHEN 'medium'"
Fixed, this was a mistake.

2020-09-16 17:10 UTC, mattmundell approved these changes

2020-09-22 21:50 UTC, merged