Fix SQL errors in SCAP and CERT update (20.08)
greenbone/gvmd pull request #1343
Opened 2020-11-03 16:30 UTC by timopollmeier

**What**:
* The update of the CVSS score for CERT advisories is only run when the SCAP schema also exists
* Schema prefixes for tables are added to SCAP and CERT alert checks

**Why**:
This fixes two SQL errors that could when updating the SCAP and CERT data:
* If the CERT update finishes without the SCAP schema existing, e.g. during the first update, the error would be the `scap.cves` table not existing.
* If the SCAP and CERT alert checks are run after the update, the `search_path` may only include the default schema, so tables like `cves` are not found without a prefix (`scap.`).

**How**:
Tested by stopping gvmd, dropping the schemas `cert` and `scap`, then restarting gvmd to make it rebuild both schemas.

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/gvmd/blob/master/CHANGELOG.md) Entry

2020-11-03 17:02 UTC, mattmundell requested changes

2020-11-04 05:45 UTC, cfi-gb commented
I guess this also replaces (at least parts or) #1295 ? Maybe worth to have a look at the PR.

2020-11-04 07:35 UTC, timopollmeier commented on src/manage_sql_secinfo.c
>    last_scap_update = 0;
Okay, I've changed it in db3a90699b2d56e2f703719d199507afbc810be5.

2020-11-04 07:39 UTC, timopollmeier commented
> I guess this also replaces (at least parts or) #1295 ? Maybe worth to have a look at the PR.

Yes, there is some overlap but #1295 also changes some other table selections in the SQL.

2020-11-04 09:40 UTC, mattmundell approved these changes

2020-11-04 09:40 UTC, merged