Clean up hosts strings before using them (20.08)
greenbone/gvmd pull request #1352
Opened 2020-11-12 15:00 UTC by timopollmeier

**What**:
Before sending hosts strings to the OSPd-OpenVAS scanner and before
calculating the number of hosts, leading zeroes in IPv4 addresses
are removed.

**Why**:
The addresses would be considered invalid otherwise, resulting in the hosts count to be reported as -1.
Starting a scan with a target using an IPv4 address with leading zeroes would also cause the scanner to crash.

**How**:
This was tested by:
1. Calling the `max_hosts` SQL function containing IPv4 addresses with extra zeroes, e.g.
`SELECT max_hosts('192.168.123.001-192.168.123.035', '192.168.123.033');`
`SELECT max_hosts('192.168.123.000/26, host001.example.com, 127.000.000.001', '');`
which should now return a positive number of hosts instead of -1.
2. Creating a target, modifying it via SQL to use a IPv4 address with extra zeroes.
(e.g. `UPDATE targets SET hosts='192.168.123.045' WHERE name='ipv4test';`)
A scan using it should run the same as one with the same address without extra zeroes and not end in the "Interrupted" status.
3. Temporarily adding extra debug output to functions where the new `clean_hosts_string` function was added to verify IPv4 addresses are cleaned up in the cases for single addresses, simple host ranges (e.g. 192.168.123.001-192.168.123.035) and CIDR notation ranges are handled while extra zeroes in hostnames like host001.example.com are kept intact. 

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/gvmd/blob/master/CHANGELOG.md) Entry

2020-11-16 06:55 UTC, ArnoStiefvater commented
Would it be a good idea to add this function to the gvm-libs/base/hosts.c ?
And some tests would be nice for this function as they should be easy to write (see gvm-libs/base/networking_tests.c).

2020-11-16 11:02 UTC, mattmundell requested changes

2020-11-16 11:04 UTC, mattmundell commented
> Would it be a good idea to add this function to the gvm-libs/base/hosts.c ?

Maybe yes.  Our rule from way back is that it only goes in libs when it's used by two modules.

> And some tests would be nice for this function as they should be easy to write (see gvm-libs/base/networking_tests.c).

Agreed.

2020-11-16 12:28 UTC, ArnoStiefvater commented
> > Would it be a good idea to add this function to the gvm-libs/base/hosts.c ?
> 
> Maybe yes. Our rule from way back is that it only goes in libs when it's used by two modules.

Maybe `gvm_hosts_t * gvm_hosts_new_with_max (const gchar *hosts_str, unsigned int max_hosts)` should be using this function to sanitize the string?

2020-11-17 09:51 UTC, timopollmeier commented on src/manage_utils.c
> +  clean_exclude_hosts = clean_hosts_string (exclude_hosts);
I've changed this in f3cd902

2020-11-17 09:52 UTC, timopollmeier commented on src/manage.c
> +  clean_hosts = clean_hosts_string (hosts_str);
The strings are now freed with 9963f83

2020-11-17 10:15 UTC, timopollmeier commented on src/manage_utils.c
> +          new_item = g_regex_replace (ipv4_replace_regex,
I've added some comments about the regular expressions in 6b267a3

2020-11-17 10:19 UTC, timopollmeier commented on src/manage_utils.c
> +                                  "(?:\\/[0-9]+|-[0-9]+(?:\\.[0-9]+){3})?$",
I think it's not really necessary, but I found it neater to not have any group matches when testing the regexp.

2020-11-17 12:41 UTC, mattmundell commented on src/manage_utils.c
> +                                  "(?:\\/[0-9]+|-[0-9]+(?:\\.[0-9]+){3})?$",
They made it harder for me to understand the regex, partly because I'm not used to them, but not a big deal.

2020-11-17 13:51 UTC, timopollmeier commented
I've added some unit tests and fixed a problem with non-leading zeroes being removed that I found with one of the test cases.

2020-11-17 13:59 UTC, mattmundell approved these changes

2020-11-17 13:59 UTC, merged