Add auto retry on scanner connection lost during a runnning task
greenbone/gvmd pull request #1452
Opened 2021-03-17 15:41 UTC by jjnicola

**What**:
￼Add auto retry on scanner connection lost during a runnning task

**Why**:
During a running scan, gvmd set immediately the task as "stopped". This patch adds an option to retry to connect.

**How did you test it**:
- Start a scan.
- chmod the ospd-openvas socket with 400 permission.
- check the logs
- 

**Checklist**:

- [ ] Tests
- [X] [CHANGELOG](https://github.com/greenbone/gvmd/blob/master/CHANGELOG.md) Entry

2021-03-18 08:07 UTC, timopollmeier requested changes
Overall this looks okay aside from a few possible improvements to the documentation and two other small issues.

2021-03-18 08:07 UTC, timopollmeier commented on doc/gvmd.8.xml
> +        <p>During a running task, number of auto retry on scanner connection
I think a better way to phrase this would be
"Number of auto retries if scanner connection is lost in a running task."

2021-03-18 08:07 UTC, timopollmeier commented on src/manage.c
> + * @brief Get the number of retry on a scanner connection lost.
This and the other comments below should say "number of retries" instead of "number of retry".

2021-03-18 11:14 UTC, timopollmeier approved these changes

2021-03-18 11:15 UTC, merged

2021-03-19 07:17 UTC, cfi-gb commented
@jjnicola @timopollmeier Could this also solve https://github.com/greenbone/gvmd/issues/1188 ?