switch to setproctitle
greenbone/gvmd pull request #1812
Opened 2022-04-28 12:42 UTC by nichtsfrei

Refactor: move from gvm-lib proctitle-set to libbsd setproctitle

To be less dependenct on gvm-libs and have more robust way to set
proctitle this commit switches from gvm-libs proctitle-set to
setproctitle of libbsd.

2022-05-03 11:23 UTC, bjoernricks requested changes
The docker image needs an update for the new dependency too

2022-05-03 11:35 UTC, bjoernricks commented
> The docker image needs an update for the new dependency too

Ah sorry it has been added in a previous commit already.

2022-05-03 11:35 UTC, bjoernricks approved these changes

2022-05-03 11:39 UTC, merged

2022-05-03 12:23 UTC, bjoernricks commented
Btw. an update for the container images was actually necessary https://github.com/greenbone/gvmd/commit/72ced60547f2e58b9031b5c7f6c9838e6744dbe8

2023-09-04 14:49 UTC, cfi-gb commented
It seems this change has introduced a duplicated `gvmd: gvmd:` in the process tile like e.g.:

```
gvmd         926  0.0  3.3 429024 273760 ?       SLs  Jun15  18:45 gvmd: gvmd: Wa  --foreground *snip*
```

which has been solved via #2065 now.