Fixed the number of results in triggered alerts.
greenbone/gvmd pull request #1895
Opened 2022-12-30 12:44 UTC by jhelmold

Fixed the number of results in triggered alerts.

**What**:
Now the number of results for automatically triggered alerts and manually triggered alerts are the same.

**Why**:
This is a bug-fix. Addresses T4-420

**How did you test it**:

**Checklist**:

- [ ] Tests
- [ ] PR merge commit message adjusted

2022-12-30 12:53 UTC, jhelmold commented
https://jira.greenbone.net/browse/T4-420

2023-01-09 14:36 UTC, timopollmeier requested changes

2023-01-09 14:36 UTC, timopollmeier commented on src/manage_sql.c
> +	}
I think this should apply to all cases where an alert is used and the filter should be set in the function calling `manage_send_report` if an alert_id is set. In that case a there may also be a filter defined by the alert that should be used.

2023-01-12 22:18 UTC, y0urself commented
@jhelmold you should enable Auto-merge (squash) when you are done with your PR and use a proper conventional commit message for this. Thank you. :)

2023-01-13 07:38 UTC, timopollmeier approved these changes

2023-01-13 07:38 UTC, merged