Change: move GET iterator time conversion out of SQL
greenbone/gvmd pull request #2112
Opened 2023-11-27 18:18 UTC by mattmundell

## What

Move the ISO time calculations in the "GET" iterators from SQL to C.

## Why

Having the SQL do the time conversion is slower when there are many rows with a large offset, because Postgres still does the time conversion for every row.

`time o m m '<get_info type="nvt" filter="sort-reverse=created rows=10 first=80000"/>' > /tmp/info`
patch 0.2, 0.2, 0.16
main  1.8, 2.2, 1.7

Leads to faster SecInfo pages when paging to the end, CPEs in particular.

## References

https://www.postgresql.org/docs/current/queries-limit.html 7.6 LIMIT and OFFSET:
`The rows skipped by an OFFSET clause still have to be computed inside the server; therefore a large OFFSET might be inefficient.`

2023-12-11 08:49 UTC, timopollmeier requested changes
This looks like a good optimization but there is one thing I'd do differently:

I think it would be better to make the allocation of new strings that need to be freed by the caller more explicit.

My suggestion would be to return an int64 from the iterator function and pass that to a new function that does both the ISO date-time conversion and the allocation.

2023-12-12 13:19 UTC, mattmundell commented
> I think it would be better to make the allocation of new strings that need to be freed by the caller more explicit.
> 
> My suggestion would be to return an int64 from the iterator function and pass that to a new function that does both the ISO date-time conversion and the allocation.

Good idea. I've started with [c1aa6f2](https://github.com/greenbone/gvmd/pull/2112/commits/c1aa6f27c28e71354f6a7994c5762117ad47a7a5). Will get back to it next week.

2023-12-18 14:20 UTC, mattmundell commented
I think the clang-format config should change to allow breaks after the return type of short definitions.

2023-12-18 15:41 UTC, mattmundell commented
> I think the clang-format config should change to allow breaks after the return type of short definitions.

Hmm, .clang-format already has AlwaysBreakAfterReturnType All.

2024-01-02 13:27 UTC, mattmundell commented
> Hmm, .clang-format already has AlwaysBreakAfterReturnType All.

Due to a clang-format limitation, see https://github.com/llvm/llvm-project/pull/76206#issuecomment-1871051642. Worked around in [cb983df](https://github.com/greenbone/gvmd/pull/2112/commits/cb983dfada959f0f73bfed7a438e5c79898408d6).

2024-02-26 14:59 UTC, a-h-abdelsalam reviewed
Looks good! You may want to update report_configs as well after updating the branch.

2024-02-27 12:04 UTC, mattmundell commented on src/gmp.c
> +                                  iso_time (&modification_time) ?: "");
The effect is the same, because modification_time is checked on the line above.

2024-02-27 12:06 UTC, mattmundell commented on src/gmp.c
> +                              iso_time (&creation_time) ?: "");
As above, iso_if_time will always call iso_time here, because creation_time is always NULL (it's check on the previous line).

2024-02-27 12:38 UTC, mattmundell commented on src/utils.c
> +    return iso_time (&epoch_time);
Yes good idea, that matches the SQL iso_time better. Done in [469a03d](https://github.com/greenbone/gvmd/pull/2112/commits/469a03dc1b6b0eb012855099bd620d3689a86809).

2024-02-27 15:02 UTC, mattmundell commented
> Looks good! You may want to update report_configs as well after updating the branch.

Thanks for going through this big PR.  Report configs part done in [be66e2e](https://github.com/greenbone/gvmd/pull/2112/commits/be66e2eb308e6d5c15b6ff944ca6da1881766c23).

2024-02-28 15:45 UTC, a-h-abdelsalam approved these changes

2024-02-28 15:58 UTC, merged