Add: Add new Report Config data type
greenbone/gvmd pull request #2136
Opened 2024-02-14 09:58 UTC by timopollmeier

## What

This adds the new data type Report Config and the corresponding GMP commands create_report_config, delete_report_config, get_report_configs and modify_report_config.

## Why
This will later allow configuring the parameters of predefined report formats when exporting reports or setting up alerts.

## References
GEA-416

2024-02-16 15:07 UTC, a-h-abdelsalam requested changes

2024-02-16 15:07 UTC, a-h-abdelsalam commented on src/schema_formats/XML/GMP.xml.in
Should the GMP version increase ?

2024-02-16 16:00 UTC, a-h-abdelsalam commented on src/manage_sql_report_configs.c
> +                    report_config_t* new_report_format)
I think it was meant to be new_report_config

2024-02-19 10:02 UTC, timopollmeier commented on src/manage_sql_report_configs.c
> +     "report_format",                                                       \
For filters `..._id` refers to the UUID of the resource, so I'll rename it to `report_format_rowid` to avoid conflict.

2024-02-19 10:24 UTC, timopollmeier commented on src/schema_formats/XML/GMP.xml.in
Previously we only updated it for changes that were incompatible with the older versions.

2024-02-19 15:52 UTC, a-h-abdelsalam requested changes

2024-02-19 15:52 UTC, a-h-abdelsalam commented on src/manage_sql.c
I came across this while reviewing GSA changes. Trying to create a filter of type report_config fails with `Type must be a valid GMP type` error. You may want to update `valid_type` and `type_db_name` functions to allow the new filter type.

2024-02-20 08:28 UTC, merged