Add: New option --max-concurrent-scan-updates
greenbone/gvmd pull request #2271
Opened 2024-07-25 14:03 UTC by timopollmeier

## What
The new startup option --max-concurrent-scan-updates is added which allows limiting the number of scan updates which can run at the same time.

## Why
This can be used to limit the peak memory and CPU usage when running multiple scans at the same time.

## References
GEA-179

2024-07-29 07:29 UTC, a-h-abdelsalam commented on src/manage.c
> +      return -1;
```suggestion
      g_free (key_file_name);
      return -1;
```

2024-07-29 07:29 UTC, a-h-abdelsalam commented on src/manage.c
> + * @param[in]  op_value   The operation value
`timeout` parameter and return value could be added to the description.

2024-07-29 07:29 UTC, a-h-abdelsalam commented on src/manage.c
> + */
return value could be added to the description.

2024-07-29 07:56 UTC, mattmundell requested changes

2024-07-29 07:56 UTC, mattmundell commented on src/manage.c
> +/* Inter-Process Communication */
Could we move this section to a new file? It looks self contained and manage.c is already large.

2024-07-29 08:31 UTC, mattmundell commented on src/manage.c
> +                                (Linux-specific) */
```suggestion
  int val;                ///< Value for SETVAL
  struct semid_ds *buf;   ///< Buffer for IPC_STAT, IPC_SET
  unsigned short *array;  ///< Array for GETALL, SETALL
  struct seminfo *__buf;  ///< Buffer for IPC_INFO (Linux-specific)
```

2024-07-30 10:31 UTC, mattmundell submitted a review, later dismissed

2024-07-30 10:31 UTC, mattmundell commented on src/manage.c
> +    int              val;    ///< Value for SETVAL
This is still indenting by 4 whereas all our `typedef struct`s and functions etc indent by 2.

I can understand breaking the convention to line up the field names though, if you like those.

2024-08-29 06:51 UTC, merged