Add: Added a new CVE scan method with the new CPE matching.
greenbone/gvmd pull request #2294
Opened 2024-09-23 09:16 UTC by jhelmold

## What
Added a new CVE scan method with the new CPE matching.

## Why
These new functions are needed for the new CVE scans with JSON match rules for CPE matching.

## ReferenceGEA-626

## Checklist

Tested manually on my local development system.
- [ ] Tests

2024-10-07 08:07 UTC, mattmundell commented on src/manage_sql.c
> +  g_message ("PROTO1: %s", levels);
Looks like stray tracing.

2024-10-07 10:11 UTC, mattmundell requested changes
Looks like a good change.

2024-10-07 10:11 UTC, mattmundell commented on src/manage.c
> +        vsi = g_strdup (cpe_match_range_iterator_version_start_incl(&cpe_match_ranges));
```suggestion
        vsi = g_strdup (cpe_match_range_iterator_version_start_incl (&cpe_match_ranges));
```
and more below

2024-10-21 10:46 UTC, mattmundell commented on src/manage.c
>              {
Nice, thanks.

2024-10-21 11:24 UTC, mattmundell commented on src/manage_sql.c
> +  if (strchr (levels, 'd'))
Thanks for removing 'd', but I really think 'e' should be in a separate PR with an explanation.

Has this additional level been agreed on? Should it be added to the GMP doc? Does it affect delta reports? Should `manage_report_filter_controls` mention it? How about a `<filter>Error</filter>` in `print_report_xml_start`? Does the gsad levels validator need adjustment? Does GSA need a checkbox for it? It definitely should be mentioned in the docs of `where_levels_auto`.

Note that there's already a separate mechanism for returning errors in reports, see `print_report_errors_xml`.

2024-10-21 11:27 UTC, mattmundell commented on src/manage_sql_secinfo.c
> + * @param[in]  root_id    The id of the root of the tree. If this value
still missing.

2024-10-21 20:46 UTC, mattmundell commented
@jhelmold I replied above, in case github is hiding them.

2024-10-22 08:21 UTC, jhelmold commented on src/manage_sql.c
> +  if (strchr (levels, 'd'))
I discussed this topic with Timo. We decided not to support any option like "d" or "e" for the display of errors. So I removed also the "e" option.

2024-10-22 10:03 UTC, mattmundell approved these changes

2024-10-24 07:35 UTC, merged